spring:
  datasource:
    url: jdbc:oracle:thin:@127.0.0.1:1521:XE
    username: scott
    password: tiger
    driver-class-name: oracle.jdbc.driver.OracleDriver

  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: false
